name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          tags: shopify-automation:latest

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "shopify-automation:latest"

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Release
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          changelog-generator-opt: "emojis=true"
          changelog-file: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - run: |
          echo "Version: ${{ steps.semrel.outputs.version }}"
          echo "Major Version: ${{ steps.semrel.outputs.version_major }}"
          echo "Minor Version: ${{ steps.semrel.outputs.version_minor }}"
          echo "Patch Version: ${{ steps.semrel.outputs.version_patch }}"
          echo "Changelog: ${{ steps.semrel.outputs.changelog }}"

      - name: Tag and push Docker image to GHCR
        run: |
          VERSION=${{ steps.semrel.outputs.version }}
          docker tag shopify-automation:latest ghcr.io/${{ github.repository_owner }}/shopify-automation:latest
          docker push ghcr.io/${{ github.repository_owner }}/shopify-automation:latest
